[tool.poetry]
name = "kot"
version = "0.1.0"
description = ""
authors = ["takaiyuk"]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "4.11.1"
click = "8.0.4"
selenium = "4.2.0"
requests = "2.27.1"
typer = "0.4.1"
webdriver-manager = "3.5.3"
PyYAML = "6.0"

[tool.poetry.dev-dependencies]
mypy = "^0.960"
pytest = "^7.1.2"
pytest-mock = "^3.7.0"
pydeps = "^1.10.18"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
