name: Dockerfile linter

on: [push]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Pull hadolint image
      run: docker pull hadolint/hadolint
    - name: Run hadolint
      run: docker run --rm -i hadolint/hadolint < Dockerfile
    - name: Build
      run: docker build . -t takaiyuk/scrape-kot
