name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
    - name: Run mypy
      run: |
        pip install mypy
        mypy kot --install-types --non-interactive && mypy kot
    - name: Run pytest
      run: |
        pip install pytest pytest-mock
        pytest tests
